name: Test API

on: [push]

jobs:
  test:
    runs-on: macOS

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install fastapi[all]
          pip install pytest

      - name: Run tests
        run: pytest -v
